/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AppToolkitRouteImport } from './routes/app/toolkit'
import { Route as AppQrCodesRouteImport } from './routes/app/qr-codes'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as ROrganizationSlugQrSlugRouteImport } from './routes/r.$organizationSlug.$qrSlug'
import { Route as AppUserUserIdRouteImport } from './routes/app/user.$userId'
import { Route as AppTeamTeamIdRouteImport } from './routes/app/team.$teamId'
import { Route as AppSettingsTeamsRouteImport } from './routes/app/settings/teams'
import { Route as AppSettingsSecurityRouteImport } from './routes/app/settings/security'
import { Route as AppSettingsProfileRouteImport } from './routes/app/settings/profile'
import { Route as AppSettingsMembersRouteImport } from './routes/app/settings/members'
import { Route as AppSettingsBillingRouteImport } from './routes/app/settings/billing'
import { Route as AppSettingsApiKeysRouteImport } from './routes/app/settings/api-keys'
import { Route as AppQrCodesNewRouteImport } from './routes/app/qr-codes.new'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiSettingsApiKeysRouteImport } from './routes/api/settings/api-keys'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppQrCodesQrCodeIdEditRouteImport } from './routes/app/qr-codes.$qrCodeId.edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppToolkitRoute = AppToolkitRouteImport.update({
  id: '/toolkit',
  path: '/toolkit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQrCodesRoute = AppQrCodesRouteImport.update({
  id: '/qr-codes',
  path: '/qr-codes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ROrganizationSlugQrSlugRoute = ROrganizationSlugQrSlugRouteImport.update({
  id: '/r/$organizationSlug/$qrSlug',
  path: '/r/$organizationSlug/$qrSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUserUserIdRoute = AppUserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTeamTeamIdRoute = AppTeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsTeamsRoute = AppSettingsTeamsRouteImport.update({
  id: '/settings/teams',
  path: '/settings/teams',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsMembersRoute = AppSettingsMembersRouteImport.update({
  id: '/settings/members',
  path: '/settings/members',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsApiKeysRoute = AppSettingsApiKeysRouteImport.update({
  id: '/settings/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQrCodesNewRoute = AppQrCodesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppQrCodesRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsApiKeysRoute = ApiSettingsApiKeysRouteImport.update({
  id: '/api/settings/api-keys',
  path: '/api/settings/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppQrCodesQrCodeIdEditRoute = AppQrCodesQrCodeIdEditRouteImport.update({
  id: '/$qrCodeId/edit',
  path: '/$qrCodeId/edit',
  getParentRoute: () => AppQrCodesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/og': typeof ApiOgRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/qr-codes': typeof AppQrCodesRouteWithChildren
  '/app/toolkit': typeof AppToolkitRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/settings/api-keys': typeof ApiSettingsApiKeysRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/qr-codes/new': typeof AppQrCodesNewRoute
  '/app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/members': typeof AppSettingsMembersRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/settings/teams': typeof AppSettingsTeamsRoute
  '/app/team/$teamId': typeof AppTeamTeamIdRoute
  '/app/user/$userId': typeof AppUserUserIdRoute
  '/r/$organizationSlug/$qrSlug': typeof ROrganizationSlugQrSlugRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/qr-codes/$qrCodeId/edit': typeof AppQrCodesQrCodeIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/og': typeof ApiOgRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/qr-codes': typeof AppQrCodesRouteWithChildren
  '/app/toolkit': typeof AppToolkitRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/settings/api-keys': typeof ApiSettingsApiKeysRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/qr-codes/new': typeof AppQrCodesNewRoute
  '/app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/members': typeof AppSettingsMembersRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/settings/teams': typeof AppSettingsTeamsRoute
  '/app/team/$teamId': typeof AppTeamTeamIdRoute
  '/app/user/$userId': typeof AppUserUserIdRoute
  '/r/$organizationSlug/$qrSlug': typeof ROrganizationSlugQrSlugRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/qr-codes/$qrCodeId/edit': typeof AppQrCodesQrCodeIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/og': typeof ApiOgRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/qr-codes': typeof AppQrCodesRouteWithChildren
  '/app/toolkit': typeof AppToolkitRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/settings/api-keys': typeof ApiSettingsApiKeysRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/qr-codes/new': typeof AppQrCodesNewRoute
  '/app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/members': typeof AppSettingsMembersRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/settings/teams': typeof AppSettingsTeamsRoute
  '/app/team/$teamId': typeof AppTeamTeamIdRoute
  '/app/user/$userId': typeof AppUserUserIdRoute
  '/r/$organizationSlug/$qrSlug': typeof ROrganizationSlugQrSlugRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/qr-codes/$qrCodeId/edit': typeof AppQrCodesQrCodeIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/privacy'
    | '/terms'
    | '/api/og'
    | '/app/analytics'
    | '/app/qr-codes'
    | '/app/toolkit'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/app/'
    | '/api/auth/$'
    | '/api/settings/api-keys'
    | '/api/trpc/$'
    | '/app/qr-codes/new'
    | '/app/settings/api-keys'
    | '/app/settings/billing'
    | '/app/settings/members'
    | '/app/settings/profile'
    | '/app/settings/security'
    | '/app/settings/teams'
    | '/app/team/$teamId'
    | '/app/user/$userId'
    | '/r/$organizationSlug/$qrSlug'
    | '/app/settings/'
    | '/app/qr-codes/$qrCodeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/api/og'
    | '/app/analytics'
    | '/app/qr-codes'
    | '/app/toolkit'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/app'
    | '/api/auth/$'
    | '/api/settings/api-keys'
    | '/api/trpc/$'
    | '/app/qr-codes/new'
    | '/app/settings/api-keys'
    | '/app/settings/billing'
    | '/app/settings/members'
    | '/app/settings/profile'
    | '/app/settings/security'
    | '/app/settings/teams'
    | '/app/team/$teamId'
    | '/app/user/$userId'
    | '/r/$organizationSlug/$qrSlug'
    | '/app/settings'
    | '/app/qr-codes/$qrCodeId/edit'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/privacy'
    | '/terms'
    | '/api/og'
    | '/app/analytics'
    | '/app/qr-codes'
    | '/app/toolkit'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/app/'
    | '/api/auth/$'
    | '/api/settings/api-keys'
    | '/api/trpc/$'
    | '/app/qr-codes/new'
    | '/app/settings/api-keys'
    | '/app/settings/billing'
    | '/app/settings/members'
    | '/app/settings/profile'
    | '/app/settings/security'
    | '/app/settings/teams'
    | '/app/team/$teamId'
    | '/app/user/$userId'
    | '/r/$organizationSlug/$qrSlug'
    | '/app/settings/'
    | '/app/qr-codes/$qrCodeId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiOgRoute: typeof ApiOgRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSettingsApiKeysRoute: typeof ApiSettingsApiKeysRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ROrganizationSlugQrSlugRoute: typeof ROrganizationSlugQrSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/toolkit': {
      id: '/app/toolkit'
      path: '/toolkit'
      fullPath: '/app/toolkit'
      preLoaderRoute: typeof AppToolkitRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/qr-codes': {
      id: '/app/qr-codes'
      path: '/qr-codes'
      fullPath: '/app/qr-codes'
      preLoaderRoute: typeof AppQrCodesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/r/$organizationSlug/$qrSlug': {
      id: '/r/$organizationSlug/$qrSlug'
      path: '/r/$organizationSlug/$qrSlug'
      fullPath: '/r/$organizationSlug/$qrSlug'
      preLoaderRoute: typeof ROrganizationSlugQrSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/user/$userId': {
      id: '/app/user/$userId'
      path: '/user/$userId'
      fullPath: '/app/user/$userId'
      preLoaderRoute: typeof AppUserUserIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/team/$teamId': {
      id: '/app/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/app/team/$teamId'
      preLoaderRoute: typeof AppTeamTeamIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/teams': {
      id: '/app/settings/teams'
      path: '/settings/teams'
      fullPath: '/app/settings/teams'
      preLoaderRoute: typeof AppSettingsTeamsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/security': {
      id: '/app/settings/security'
      path: '/settings/security'
      fullPath: '/app/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/profile': {
      id: '/app/settings/profile'
      path: '/settings/profile'
      fullPath: '/app/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/members': {
      id: '/app/settings/members'
      path: '/settings/members'
      fullPath: '/app/settings/members'
      preLoaderRoute: typeof AppSettingsMembersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/billing': {
      id: '/app/settings/billing'
      path: '/settings/billing'
      fullPath: '/app/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/api-keys': {
      id: '/app/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/app/settings/api-keys'
      preLoaderRoute: typeof AppSettingsApiKeysRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/qr-codes/new': {
      id: '/app/qr-codes/new'
      path: '/new'
      fullPath: '/app/qr-codes/new'
      preLoaderRoute: typeof AppQrCodesNewRouteImport
      parentRoute: typeof AppQrCodesRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/api-keys': {
      id: '/api/settings/api-keys'
      path: '/api/settings/api-keys'
      fullPath: '/api/settings/api-keys'
      preLoaderRoute: typeof ApiSettingsApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/qr-codes/$qrCodeId/edit': {
      id: '/app/qr-codes/$qrCodeId/edit'
      path: '/$qrCodeId/edit'
      fullPath: '/app/qr-codes/$qrCodeId/edit'
      preLoaderRoute: typeof AppQrCodesQrCodeIdEditRouteImport
      parentRoute: typeof AppQrCodesRoute
    }
  }
}

interface AppQrCodesRouteChildren {
  AppQrCodesNewRoute: typeof AppQrCodesNewRoute
  AppQrCodesQrCodeIdEditRoute: typeof AppQrCodesQrCodeIdEditRoute
}

const AppQrCodesRouteChildren: AppQrCodesRouteChildren = {
  AppQrCodesNewRoute: AppQrCodesNewRoute,
  AppQrCodesQrCodeIdEditRoute: AppQrCodesQrCodeIdEditRoute,
}

const AppQrCodesRouteWithChildren = AppQrCodesRoute._addFileChildren(
  AppQrCodesRouteChildren,
)

interface AppRouteRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppQrCodesRoute: typeof AppQrCodesRouteWithChildren
  AppToolkitRoute: typeof AppToolkitRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsApiKeysRoute: typeof AppSettingsApiKeysRoute
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsMembersRoute: typeof AppSettingsMembersRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsTeamsRoute: typeof AppSettingsTeamsRoute
  AppTeamTeamIdRoute: typeof AppTeamTeamIdRoute
  AppUserUserIdRoute: typeof AppUserUserIdRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppQrCodesRoute: AppQrCodesRouteWithChildren,
  AppToolkitRoute: AppToolkitRoute,
  AppIndexRoute: AppIndexRoute,
  AppSettingsApiKeysRoute: AppSettingsApiKeysRoute,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsMembersRoute: AppSettingsMembersRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsTeamsRoute: AppSettingsTeamsRoute,
  AppTeamTeamIdRoute: AppTeamTeamIdRoute,
  AppUserUserIdRoute: AppUserUserIdRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiOgRoute: ApiOgRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSettingsApiKeysRoute: ApiSettingsApiKeysRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ROrganizationSlugQrSlugRoute: ROrganizationSlugQrSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
